/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "transfer.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void
file_transfer_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		file_data upload_file_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case UPLOAD_FILE:
		_xdr_argument = (xdrproc_t) xdr_file_data;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) upload_file_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
    register SVCXPRT *transp;

    /* Xóa đăng ký cũ nếu có */
    pmap_unset (FILE_TRANSFER_PROG, V1);

    /* 1. Tạo Server UDP (Vì Client bạn dùng UDP) */
    transp = svcudp_create(RPC_ANYSOCK);
    if (transp == NULL) {
        fprintf (stderr, "%s", "cannot create udp service.");
        exit(1);
    }
    if (!svc_register(transp, FILE_TRANSFER_PROG, V1, file_transfer_prog_1, IPPROTO_UDP)) {
        fprintf (stderr, "%s", "unable to register (FILE_TRANSFER_PROG, V1, udp).");
        exit(1);
    }

    /* 2. Tạo Server TCP (Dự phòng) */
    transp = svctcp_create(RPC_ANYSOCK, 0, 0);
    if (transp == NULL) {
        fprintf (stderr, "%s", "cannot create tcp service.");
        exit(1);
    }
    if (!svc_register(transp, FILE_TRANSFER_PROG, V1, file_transfer_prog_1, IPPROTO_TCP)) {
        fprintf (stderr, "%s", "unable to register (FILE_TRANSFER_PROG, V1, tcp).");
        exit(1);
    }

    /* 3. Vòng lặp lắng nghe */
    svc_run ();
    fprintf (stderr, "%s", "svc_run returned");
    exit (1);
    /* NOTREACHED */
}
